# Generated by Django 4.2 on 2025-06-03 12:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('yearly_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('feature_1', models.CharField(max_length=255)),
                ('feature_2', models.CharField(max_length=255)),
                ('feature_3', models.CharField(max_length=255)),
                ('feature_4', models.CharField(max_length=255)),
                ('feature_5', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('yearly_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('feature_1', models.CharField(max_length=255)),
                ('feature_2', models.CharField(max_length=255)),
                ('feature_3', models.CharField(max_length=255)),
                ('feature_4', models.CharField(max_length=255)),
                ('feature_5', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OneTimePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onetime_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('yearly_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('feature_1', models.CharField(max_length=255)),
                ('feature_2', models.CharField(max_length=255)),
                ('feature_3', models.CharField(max_length=255)),
                ('feature_4', models.CharField(max_length=255)),
                ('feature_5', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('selected_plans', models.JSONField(blank=True, null=True)),
                ('total_users', models.IntegerField(default=0)),
                ('selected_devices', models.JSONField(blank=True, null=True)),
                ('port_numbers_enabled', models.BooleanField(default=False)),
                ('port_numbers', models.TextField(blank=True, null=True)),
                ('need_phone_numbers', models.BooleanField(default=False)),
                ('need_toll_free_numbers', models.BooleanField(default=False)),
                ('area_code', models.CharField(blank=True, max_length=20, null=True)),
                ('installation_type', models.CharField(blank=True, max_length=100, null=True)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(upload_to='products/')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearly_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('yearly_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('monthly_equivalent_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('feature_1', models.CharField(max_length=255)),
                ('feature_2', models.CharField(max_length=255)),
                ('feature_3', models.CharField(max_length=255)),
                ('feature_4', models.CharField(max_length=255)),
                ('feature_5', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('voice', 'Business Voice'), ('safety', 'Business Safety')], max_length=10)),
                ('duration', models.IntegerField(choices=[(1, '1 Year'), (2, '2 Years')], default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
