# Generated by Django 4.2 on 2025-06-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eazyyapp', '0002_order_account_info_order_email_order_user_allocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='port_numbers_enabled',
            new_name='porting_enabled',
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
