# Generated by Django 4.2 on 2025-06-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eazyyapp', '0003_rename_port_numbers_enabled_order_porting_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='usage_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
