# Generated by Django 4.2 on 2025-06-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eazyyapp', '0005_alter_order_city_alter_order_postal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
